#!/usr/local/bin/php
<?
require("../../../include/var.inc");
$localpath="/zivido";
require("../../../include/counter.inc");
?>
<html>
<head>
<title>FrancescoI°</title>
<link href="/zivido/zivido.css" rel="stylesheet" type="text/css">
</head>
<body>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="80%" align="left" valign="top"><img src="/zivido/images/zividologo.png" width="653" height="85"></td>
    <td width="20%" align="left" valign="bottom"><h2>i Giganti </h2></td>
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" valign="top"><img src="/zivido/images/francesco.png" width="400" height="30"></td>
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="1%">&nbsp;</td>
    <td width="26%" align="center" valign="top"><img src="france.jpg" width="207" height="257"><br>
      <table width="83%"  border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td align="left" valign="top"><p>Dipinto di Francois Clouet (+1572), Firenze, Uffizi</p></td>
        </tr>
      </table>
      <br>
    <br>
    <img src="/zivido/igiganti/personaggi/giglio.jpg" width="92" height="95"><br>
    <table width="83%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="left" valign="top"><p>Cognac 1494 - Rambouillet 1547<br>
  Re di Francia</p></td>
      </tr>
    </table>
    <br><br></td>
    <td width="35%" align="left" valign="top"><p>Figlio di Carlo di Orleans conte di Angouli&eacute;me e di Luisa di Savoia, succedette a Luigi XII di cui aveva sposato la figlia Claudia, nel momento in cui la perdita del milanese e la costante pressione degli svizzeri da un lato, la fortunata politica dinastica degli Asburgo dall'altro, minacciavano di bloccare l'espansione politica e territoriale della Francia.<br>
        La ripresa delle guerre d'Italia appariva quindi al giovane sovrano il primo dei suoi compiti: e raccolto un esercito di 30.000 uomini (un terzo di francesi e due terzi di lanzichenecchi), nell'agosto 1515 cal&ograve; in Piemonte. La sua meta era Milano, ove solo l'appoggio dei cantoni elvetici sosteneva il duca Massimiliano Sforza: a Marignano (oggi Melegnano) <span class="citazione">(<strong>ndr acz</strong>: in realt&agrave; il luogo esatto dello scontro fu il borgo di Zivido frazione del comune di San Giuliano Milanese dove ancora oggi sotto la chiesa parrocchiale riposano i resti dei caduti ed &egrave; stato collocato nel 1965, a cura di una apposita fondazione elvetica, un monumento a ricordo degli svizzeri morti. Fra il borgo di Zivido e San Giuliano Milanese Francesco I° fece edificare il monastero &quot;Della Vittoria&quot; per ottemperare al voto espresso nella tragica notte a cavallo del 13 e 14 settembre 1515. Le fondamenta del monastero sono attualmente sovrastate dal cimitero cittadino di San Giuliano Milanese)</span> l'esercito francese, cui giunse tempestivamente in soccorso quello veneziano, sbaragli&ograve; gli svizzeri (13-14 settembre).<br>
        Francesco I°, che si era battuto in prima linea a colpi di picca, fu un artefice decisivo della vittoria che ferm&ograve; la marcia degli svizzeri nella pianura padana, costrinse lo Sforza ad abdicare (4 ottobre) e consegn&ograve; alla Francia il conteso stato di Milano.<br>
        Un indiretto ma importante frutto della vittoria fu anche il concordato che papa Leone X stipul&ograve; con Francesco I° nell'agosto 1516, cedendo sia alla minaccia militare incombente sul governo mediceo di Firenze e sulla stessa Roma, sia al timore di uno scisma del clero francese, possibile dopo i concili di Pisa e del Laterano (1510 e 1512).<br>
        Il concordato deferiva al re la designazione dei benefici concistoriali, cio&egrave; dei vescovati, delle abbazie e dei priorati, mentre i benefici minori (e in primo luogo le parrocchie) rimanevano di giuspatronato vescovile, feudale e comunale, secondo le antiche consuetudini.<br>
        L'autonomia dell'alto clero rispetto alla corona subiva un colpo decisivo, poich&egrave; il re poteva disporre delle cariche prelatizie a favore dei nobili e dei suoi cortigiani. Il basso clero, mal remunerato dalle piccole prebende e in frattura spesso aperta con i vescovi aristocratici, diveniva viceversa un focolaio di malcontento che la diffusione delle idee riformate e le guerre di religione metteranno in evidenza.<br>
        Con il concordato il gallicanesimo aveva partita vinta e Francesco I° acquisiva, con la formale sanzione pontificia, un potere nel gestire gli affari e il patrimonio ecclesiastico che nessun re di Francia aveva mai avuto. Il trattato di Noyon stipulato in seguito con la Spagna (13 agosto 1516) e una serie di accordi collaterali sembravano aprire un'era di pace tra principi cristiani, ma nel 1519 la morte di Massimiliano apr&igrave; la lotta per l'elezione imperiale, cui Francesco I° si era preparato guadagnandosi pazientemente l'appoggio di molti principi tedeschi; le grandi disponibilit&agrave; finanziarie degli Asburgo e la diffidenza per l'intrusione francese nelle cose di Germania portarono per&ograve; all'elezione di Carlo V, gi&agrave; re di Spagna.<br>
        Questo evento rendeva inevitabile, per impedire l'accerchiamento asburgico, la ripresa della guerra, che nel maggio 1521 inizi&ograve; in Italia, sul Reno, in Fiandra e nei Pirenei. FrancescoI°, che riteneva Carlo V paralizzato dalle difficolt&agrave; finanziarie e incapace di fronteggiare la rivolta dei comuneros in Spagna, sub&igrave; una serie di rovesci cui reag&igrave; scendendo egli stesso in Lombardia nell'autunno 1524; il 25 febbraio 1525 l'esercito francese fu distrutto davanti a Pavia e il re, ferito a un braccio, cadde in mano agli spagnoli.<br>
        La prigionia fu subita prima a Pizzighettone poi in Spagna, sino al marzo 1526, quando la gravosa pace di Madrid liber&ograve; Francesco I°, che pot&egrave; rientrare in Francia lasciando in ostaggio i due figli e cedendo Lombardia e Borgogna.<br>
        Appena giunto a Parigi, il re si dichiar&ograve; solennemente sciolto da ogni impegno contratto in cattivit&agrave; e riusc&igrave; subito a costituire la lega di Cognac con i principi italiani, con il papa e col larvato ma tangibile appoggio turco: ma anche questa nuova fase della guerra, che ebbe il suo momento più drammatico nel sacco di Roma (1527), volse a favore di Carlo V.<br>
        Finalmente la pace di Cambrai (o delle due dame, 1529), che confermava quella di Madrid, diede alla Francia qualche anno di respiro. Riaccesa nel 1536 e interrotta nel 1538 con la tregua di Nizza la guerra ebbe nel 1542-44 un'ulteriore ripresa cui fece seguito la pace di Cr&eacute;py; ma quando Francesco I° mor&igrave; (31 marzo 1547) lasciando il trono al figlio Enrico II, il conflitto era solo provvisoriamente sopito.<br>
        Per sostenere l'enorme sforzo militare, Francesco I° accompagn&ograve; a una riforma fiscale moderatamente accentratrice una politica di appoggio alla nobilt&agrave; e di caute concessioni alla borghesia degli uffici. Solo duecento nuovi nobili furono creati durante il suo regno, mentre sulle vecchie famiglie titolate si concentrarono le cariche militari e diplomatiche e i benefici ecclesiastici di nomina regia; la fedelt&agrave; dei funzionari fu nel contempo assicurata istituendo nel 1522 l'Ufficio delle partite casuali che, pur assegnando al fisco una tangente, riconosceva la venalit&agrave; delle cariche, consentendo cos&igrave; ai titolari di negoziare i propri &quot;offici&quot; come beni patrimoniali. Il costo della guerra, combattuta talora anche su suolo francese, ricadde pesantemente sui ceti popolari delle citt&agrave; e delle campagne, provocando violente e sanguinose sommosse.<br>
        L'infiltrazione delle idee riformate, prima in Borgogna e in Guienna, poi nei centri universitari e gradualmente in tutto il paese, fu combattuta con feroce rigore da Francesco I°, specie dopo il marzo 1534 quando nei suoi appartamenti furono affissi cartelli (placards) di propaganda &quot;luterana&quot;.<br>
        Calvino ricord&ograve; invano al re nella Institutio religionis christianae (1536) che il principe non ha potere nelle cose di coscienza e che il suddito evangelico non &egrave; in quanto tale ribelle; la repressione si fece sempre più dura.<br>
        Nonostante questa intransigenza la politica estera di Francesco I° fu spregiudicata: egli ebbe infatti costanti intese con i principi luterani della Germania; strinse con l'impero ottomano dapprima un tacito accordo (1525-26), poi (1536) un trattato commerciale estremamente vantaggioso per i sudditi francesi negli scali del levante, seguito dalla congiunzione delle due flotte che incrociavano unite nel Mediterraneo, e da ulteriori operazioni di terra e di mare nel 1541 e 1542 contro gli spagnoli. Francesco I° assunse allora apertamente la responsabilit&agrave; dell'alleanza con l'infedele, facendo teorizzare dai suoi ambasciatori le giuste ragioni che tenevano la Francia in armi contro l'impero.<br>
        I trent'anni di regno di Francesco I° si chiudevano con la temporanea occupazione del Piemonte, ma con la sostanziale sconfitta delle ambizioni che avevano mobilitato cos&igrave; a lungo il paese. Per&ograve;, nonostante le guerre si fossero concluse sempre con la vittoria delle armi e della diplomazia spagnole, quella durissima prova aveva dato alla Francia una sua compagine nazionale che le aveva permesso di durare intatta.<br>
    E il re ebbe ben vivo nella sua politica culturale il senso delle dignit&agrave; e della grandezza francesi, chiamando alla sua corte Leonardo da Vinci e Benvenuto Cellini, proteggendo gli studi universitari, fondando il Coll&egrave;ge de France. Uomo d'armi e di lettere, che tante volte aveva rischiato sul campo la propria vita, che pot&egrave; essere fatto prigioniero a Pavia solo perch&egrave; ferito, che mentre mandava al rogo gli eretici negoziava con luterani e turchi, Francesco I° risolveva i suoi doveri di sovrano in termini d'onore, di splendore e di cavalleria; quel senso religioso dell'investitura monarchica, che Carlo V aveva sempre sentito, non gli era familiare.<br><br>(di Marino Berengo, Enciclopedia Europea, vol.V, 1991, Ed Garzanti)</p></td>
    <td width="3%" align="center" valign="top"><img src="/colori/DFDF00.gif" width="2" height="100%"></td>
    <td width="35%" align="left" valign="top"><p>François 1er succéda en 1515 à son cousin et beau-père Louis XII qui n'avait pas d'héritiers. Il avait en effet épousé sa fille, Claude de France l'année précédente, qui allait lui donner pour fils le futur roi Henri II. Son règne de trente-deux ans marqua profondément le XVIe siècle français, transformant à l'extérieur les guerres d'Italie en un affrontement avec les Habsbourg, donnant, à l'intérieur, une impulsion déci- sive à la pratique d'une &quot;monarchie absolue&quot;. François 1er avait une stature colossale, ce que laissent quelque peu entrevoir les célèbres portraits que l'on a de lui (Le Titien, Clouet ) ainsi que son armure gigantesque qui a été conservée jusqu'à aujourd'hui. Il mesurait presque deux mètres, ce qui faisait de lui un véritable géant, surtout à l'époque où la taille moyenne était nettement plus faible qu'aujourd'hui. François 1er était le type même de l'homme élégant de la Renaissance, vigoureux, de goûts chevaleresques, amateur de femmes et de belles choses, un peu artiste. Mais en même temps, c'est un homme fantasque, sujet aux emballements, d'une intelligence un peu superficielle. Le règne s'ouvrit sur la fin des guerres d'Italie.<br><br>
        <strong>François 1er et les guerres d'Italie</strong><br>
      Lorsque Louis XII mourut le 1er Janvier 1515, il venait de perdre le Milanais. Son cousin François 1er lui succéda, il avait alors vingt ans, et il résolut de marquer son début de règne de manière brillante en reconquérant le Milanais.<br>
    Les adversaires suisses, alliés du Duc de Milan, furent surpris par l'habileté de manoeuvre de l'armée française, et la bataille décisive eut lieu à Marignan (1515), près de Milan, durant laquelle François 1er remporta une victoire éclatante. Il se fit alors adouber chevalier par Bayard sur le champ de bataille de Marignan. Cette victoire lui permis par là-même de signer la paix avec le pape Léon X , les Suisses, et de tenir à l'écart de cette région Charles 1er, le jeune roi d'Espagne et futur Charles Quint. Ce fut la fin des guerres d'Italie, dont l'une des conséquences les plus importantes fut la Renaissance française, fille de la Renaissance Italienne.<br><br>
    <strong>La rivalité entre François 1er et Charles Quint</strong><br>
A la mort de l'empereur Maximilien d'Autriche, Charles 1er d'Espagne et François 1er posèrent tous les deux leur candidature à sa succession. Finalement, ce fut Charles qui fut élu sous le nom de Charles Quint en 1519. L'ambition de conquérant affichée par Charles Quint dès le début de son règne était une menace sérieuse pour le royaume de France, puisque l'empereur entendait reprendre les régions ayant autrefois fait partie de l'empire ( la Picardie, la Bourgogne, le Dauphiné, la Provence). Mais François 1er continuait à s'occuper de l'Italie, au lieu de se soucier des frontières du Nord et de l'Est. Ainsi, la première guerre fut désastreuse pour François 1er. A la suite de combats malheureux en Italie ou Bayard périt, François 1er s'impliqua personnellement avec une espèce de fougue un peu folle et il fut pri- sonnier à Pavie en 1525. Pour retrouver la liberté, il consentit à signer le désastreux traité de Madrid (1526) par lequel il renonçait à l'Italie et promettait de céder la Bourgogne. Cependant, il viola ce traité dès qu'il eut retrouvé la liberté, avec le soutien des Etats de Bourgogne. La guerre fut marquée par une pause lors de la&quot; paix des dames &quot;, puis s'acheva sur la constatation d'un équilibre des forces (traité de Cambrai,1529). Ayant pris la mesure de son adversaire, dans la troisième phase du conflit, François 1er chercha des alliés : le Turc Soliman le Magnifique, Henri VIII, les princes protestants allemands. L'alliance Turque parut scandaleuse, mais fut profitable militairement et commercialement. La longue lutte qui suit, confu- se et sans gloire, aboutit au traité de Crépy (1544), créant le premier et fragile équilibre européen.<br><br>
<strong>L'exercice de la monarchie sous François 1er</strong><br>
Monarque à la fois fin, éclairé, mais aussi brutal et intransigeant, en un mot ambigu, François 1er exerça le pouvoir avec fermeté et ramena la royauté dans la voie du despotisme. C'est à lui que l'on doit la formule &quot; Car tel est notre bon plaisir &quot;, qui était apposée au bas des ordonnances. C'est également sous son règne qu'apparut l'expression &quot;Votre Majesté&quot;, jusqu'alors réservée a l'empereur. Personne ne songeait sérieusement à s'opposer au roi, si ce n'est le Duc de Bourbon (appelé aussi &quot; le connétable &quot;). L'alliance que celui-ci tenta avec Charles Quint échoua, et il se vit confisqué à peu près tous ses biens. Les autres seigneurs n'avaient aucun intérêt à désobéir, et le clergé non plus. Le roi exerçait une autorité totale sur les prélats de l'église, puisque par le Concordat de Bologne (1516), le pape Léon X avait reconnu à François 1er le droit de nommer les archevêques, évêques et abbés du royaume. Dans le souci de voir son autorité incontestée, François 1er ne réunit jamais les Etats Généraux. Il écoutait même à peine les quelques remarques que le Parlement osait timidement opposer à son autorité de temps à autre. Pour traiter des affaires capitales, le roi prenait conseil auprès de quelques intimes, le Conseil des Affaires. C'est sous le règne de François 1er que se développe la Cour, dont l'apogée sera atteinte sous le règne de Louis XIV. La Cour était alors constituée de plusieurs milliers de personnes, elle exerçait une fascination certaine pour tous ceux qui enviaient l'aura de pouvoir, de plaisirs et de fêtes mêlés qui lui était attachée. La Cour était composée de fonctionnaires et domestiques au service du roi, de ceux qui l'aidaient à gouverner, des Princes de sang, et enfin tous ceux que le roi dai- gnait y appeler, selon son bon plaisir. Cependant, toutes les fêtes de la cour, les guerres incessantes, la construction des châteaux entraînaient des dépenses énor- mes, et c'est à François 1er que l'on doit le premier emprunt en 1522, et c'est éga- lement à cette date que remonte notre Dette Publique. Le désordre des finances ne fut pas résorbé pour autant, et ce mal chronique embarrassa la royauté jusqu'en 1789.<br><br>
<strong>Un artisan de la Renaissance en France</strong><br>
Au bout du compte, l'empreinte la plus marquante du monarque se situe sur le plan intellectuel et artistique. Dès son avènement, François 1er veut être reconnu comme le prince de la Renaissance. L'art nouveau sert son goût du prestige, de la magnificence, et sa volonté politique d'affirmer la grandeur du pouvoir royal. La cour de François 1er est brillante et admirée en Europe. Le roi protège humanistes, musi- ciens et poètes (Ronsard, Du Bellay, Marot, Budé, Lefèvre d'Étaples) et fonde le Collège des lecteurs royaux, qui deviendra plus tard le Collège de France. Suivant l'exemple de Charles VIII, il achète en Italie tableaux et statues antiques. C'est lui qui fait venir en France Léonard de Vinci qu'il installe au Clot-Lucé, et fait appel à d'autres grands artistes italiens tels que Benvenuto Cellini. Sur le plan architectural, le règne de François 1er est marqué surtout par la construction ou la rénovation de somptueux châteaux dans lesquels le souffle de la Renaissance s'exprime pleine- ment. François 1er fait agrandir le château de Blois. Il abandonne, délibérément, le style ancien de construction adopté par ses prédécesseurs. Le bâtiment est construit en pierre de taille et non plus en brique. La façade à galeries et arcades est inspirée de l'architecture édifiée par Bramante au Vatican. De 1520 à 1540, une nouvelle résidence royale est élevée à Chambord. La symétrie, l'harmonie de l'ensemble, le parc et les jardins en font l'un des monuments les plus remarquables de cette époque. Depuis les vastes terrasses à l'italienne, la cour suivait les départs pour la chasse dans les forêts de la Sologne, toute proche. Par la suite, après le désastre de Pavie (1554), François 1er fait construire surtout en Ile-de-France. Le château de Fontainebleau, agrandi, reçoit un décor magnifique. Deux artistes italiens, Le Rosso et Le Primatice y animent des ateliers nombreux et brillants. Fasciné par l'Italie, exactement comme d'autres, en d'autres temps, seront fascinés par l'Amérique, François 1er y a donc puisé l'âme de la Renaissance, qui a pu se développer ensuite avec son caractère propre en France. Enfin, c'est sous le règne de François 1er que la langue du royaume, le français, s'est véritablement unifiée. (Texte écrit par P.M)</p></td>
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="top"><img src="/colori/4AA5FF.jpg" width="100%" height="1"></td>
  </tr>
</table>
<p class="piepagina"><a href="igiganti.php" target="pagina">
  i Giganti</a><br>
  <br>
  <a href="/index.php"><img src="../../ppplogoacz.jpg" WIDTH="61" HEIGHT="95" border="0"></a><br>
  sito di proprietà dell'<a href="/index.php">Associazione Culturale Zivido</a><br>
<a href="mailto:webmaster@aczivido">webmaster@aczivido.net</a></p>
</body>
</html>
