#!/usr/local/bin/php
<?
require("../include/var.inc");
$localpath="/raccontami";
require("../include/counter.inc");
?><html>
<head>
<title>Il segreto di Maddalena</title>
<link href="/raccontami/raccontami.css" rel="stylesheet" type="text/css">
</head>
<body bgcolor="#FFFFFF"> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="left" valign="top" bgcolor="#005A87"><img src="/log1.png" width="590" height="97"></td>
  </tr>
  <tr>
    <td align="left" valign="top"><img src="/log2.png" width="100%" height="20"></td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#005A87"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="50%" align="left" valign="top"><img src="/raccontami.jpg" width="136" height="48"></td>
        <td width="50%" align="right" valign="top"><img src="/raccontami/madd.png" width="343" height="48"></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="left" valign="top"><img src="/log3.png" width="100%" height="20"></td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#005A87">&nbsp;</td>
  </tr>
</table>
<table width="100%"  border="0" cellpadding="0" cellspacing="0" bgcolor="#005A87">
  <tr>
    <td width="30%" align="left" valign="top"><img src="/log4.png" width="100%" height="4194"></td>
    <td width="70%" align="left" valign="top"><table width="98%"  border="0" cellpadding="0" cellspacing="5" bgcolor="#B9DCFF">
      <tr>
        <td align="left" valign="top"><h1>di Adriana Santoro. Racconto pubblicato da &quot;Il Melegnanese&quot;.</h1>
          <p>Era ferma davanti al Castello, in quella bella mattina di prima estate. Uno di quei beati giorni in cui, riposati il corpo e la mente, tra i suoni della giornata che incomincia ci si sente come trascinare in due opposte direzioni: da un lato, verso un altrove che appare seducente proprio perché vago, dall&#146;altro si è risucchiati dentro al vortice del passato a scoprire il misterioso iceberg galleggiante sul mare del tempo, fatto di ciò che è stato prima di noi e che è così intrigante portare alla luce.<br>
              Da qualche settimana le capitava spesso di transitare da lì, per svariati motivi o impegni, anzi qualche volta c&#146;era venuta apposta, come adesso. Il percorso nel verde, quasi un anticipo di vacanze, e la solenne mole che le faceva da scorta sullo sfondo del sentiero, davano a quell&#146;inizio di giornata un&#146;impronta nuova e fresca, quasi una benedizione. E poi, quanti particolari aveva potuto notare, prima trascurati: un arco, un muraglione, il profilo di una torretta, un cancello irto di punte. Pure, nessuna scoperta era paragonabile a quella di oggi. Il balconcino (ma come aveva potuto ignorarlo fino ad allora?) sorgeva isolato in alto, sul lato verso il Lambro: poco più di un rudere, il pavimento di assi semisospeso sul vuoto, il parapetto in ferro a deliziose volute tenuto in precario equilibrio da due aste infisse nel muto di sopra; lo sfondo di mattoni sbrecciati nido di piccioni e di rondini, una portafinestra senza più colore chiusa sul mistero di stanze interne da chissà quanto tempo prive di vita.<br>
              Odore di polvere, odore di passato. Quello stesso da lei sempre respirato avidamente nelle vecchie chiese (San Pietro per la prima, e il suo barocco un po&#146; rustico) e in cui si mescolano incenso vecchio, fiori sfatti, la paglia delle sedie, la cera delle candele, il colore delle tele nei quadri, penne e piume di uccelli che lì dentro hanno fatto i loro nidi, i frammenti e il respiro di chissà quali momenti vissuti da chissà quali persone.<br>
              <span class="citazione">&quot;Questo sentore è per me la strada maestra verso un mondo che in qualche modo mi appartiene. Però, rifletteva, è improprio attribuirgli adesso un odore di cose morte: quando quel mondo viveva, sicuramente era un altro il suo contrassegno. Come qui, su questo balconcino: un guscio vuoto adesso, l&#146;ombra di ciò che è stato. Ma, altro che odore di polvere quando, in un Giugno uguale a questo, con lo stesso cielo e quasi le stesse rondini, e i giardini sotto e il Lambro sullo sfondo, qualcuno (e le sembrava quasi di intravederne i contorni delle braccia, e la gonnella lunga fino alle caviglie) si sarà appoggiato a quel parapetto, per guardare lontano!&#133;&quot;.</span><br>
              Maddalena si era portata il ricamo sul balconcino e alternava le gugliate a momenti di riposo, lo sguardo perso nel cielo d&#146;una azzurro soffice come il raso del suo abito più elegante, quello con la gonna a paniere secondo la moda. A volte, si alzava e si appoggiava alla ringhiera per osservare giù nel prato il piccolo trotto dei cavalli del marchese, che un palafreniere teneva in esercizio. Seguiva anche il volo delle rondini, ascoltava il più vicino, domestico tubare dei colombi. Poco oltre la cinta, alberi, alberi e la striscia del Lambro, ricordo di belle gite in barca e di merende nei boschetti con tutta la famiglia, rallegrate dal mandolino che il padre nei momenti felici sapeva suonare così bene.<br>
              La mamma di solito preferiva che Maddalena stesse in casa con lei ad aiutarla, per scendere magari più tardi, durante la bella stagione, nella corte quando si sarebbe radunata lì tutta la casa, compreso il personale. E davvero quello era il momento in cui le barriere sociali si allentavano e poteva essere consentito scambiare quattro chiacchiere con altri giovani: di condizione civile come Maddalena, figlia di un segretario del marchese, e perfino con le domestiche, del resto sue amiche d&#146;infanzia, o addirittura con i figli del marchese quando c&#146;erano, oppure con i giovani scrivani del padre.<br>
              Maddalena, però, da qualche tempo preferiva la solitudine: quell&#146;aereo balcone, unico in tutta la facciata posteriore del castello, le dava come la sensazione di librarsi verso il cielo, lontana dalle chiacchiere serali con le amiche e dalle frasi scherzose dei giovanotti; vi coltivava in silenzio, come una pianticella delicata, un segreto che avrebbe potuto diventare &#150; lei lo sentiva &#150; una cosa grande per la sua vita. E poi, quello era un giorno speciale, in cui avrebbe dovuto congedarsi per un po' di tempo (non precisato, ma che presentiva non brevissimo) dai suoi cari, persone e cose. Per l&#146;indomani era stata infatti fissata la partenza: Maddalena sarebbe andata a Milano, ospite di una zia che da qualche giorno era a sua volta ospite loro. La madre la chiamò e lei, obbediente come sempre, si affrettò a rientrare, accostando i battenti della portafinestra perché la stanza non venisse invasa, appena accesi i lumi, dalle zanzare già numerose in quel principio di estate. Zia Caterina rientrava in quel momento dalle visite ai suoi conoscenti melegnanesi: grossa, grassa, imponente, saliva le scale ansimando seguita dal suo domestico Giobatta. Questa zia era un po&#146; l&#146;autorità della famiglia, per il prestigio sociale acquisito grazie al matrimonio con la conseguente agiatezza economica, e soprattutto per il carattere volitivo che le consentiva di dominare non solo il proprio marito, ma anche il fratello e la famiglia di quest&#146;ultimo, interferendo nelle faccende altrui considerate come sue proprie (a fin di bene, diceva lei).<br>
              <span class="citazione">&quot;Buonasera, signora zia&quot;. &quot;Buonasera, Maddalena, dovresti pettinarti con i capelli sciolti: così sembri più vecchia&quot;.</span> Maddalena non replicò all&#146;osservazione, ma anzi: <span class="citazione">&quot;Desiderate una bevanda fresca? Ve la porto subito&quot;</span> disse; e al cenno di assenso della zia si affrettò a mescere da una brocca di vetro azzurro, e a servire su un piccolo vassoio di lacca, un bicchiere colmo di sciroppo d&#146;orzo. Il locale piuttosto ampio (in uso alla loro famiglia grazie alla benevolenza del marchese) era arredato in modo semplice: sul camino due candelieri di vermeille; accanto, una poltrona per i visitatori importanti, in cui la zia aveva subito preso posto; un tavolo; accostato al muro, un cantonale; sulla parete di fianco alla portafinestra un quadro con una scena pastorale dipinta a tenui colori e, sotto, la spinetta dove Maddalena aveva posato un rotolo di musica ricevuto da pochi giorni: <i>Clementi, sonatine.</i><br>
              La conversazione si aggirò per un poco sui progressi musicali di Maddalena (a dire il vero, non eccezionali). La zia, però, non attese molto per ritornare sull&#146;argomento del loro viaggio e relativo soggiorno a Milano, indugiando a descriverne i benefici effetti su Maddalena, fine, istruita, ma troppo riservata e schiva, e in fondo, aggiunse con orgoglio di cittadina acquisita, un po&#146; sprecata lì in paese. La ragazza avrebbe potuto accompagnarla al passeggio, nelle visite, farle da lettrice, ma soprattutto avrebbe avuto lassù l&#146;opportunità di stringere delle conoscenze preziose&#133;<br>
              Quello era in realtà lo scopo occulto della proposta, noto solo ai genitori della giovane attraverso un fitto carteggio preliminare: trovare per Maddalena, ormai diciannovenne, un &quot;partito&quot;, possibilmente ricco, anche se magari rappresentato da un uomo più anziano di lei come del resto succedeva spesso. Maddalena aveva qualche innamorato lì al paese? si era informata la zia. No, non pareva,non se ne sapeva niente; e poi la ragazza, così docile e tranquilla, si darebbe di certo confidata con la madre. D&#146;altra parte non si vedeva l&#146;ombra di un pretendente serio lì intorno, dove c&#146;erano altre giovani ben più ricche e forse anche più belle di lei&#133; Allora la zia si era messa in moto e aveva già sott&#146;occhio più di una persona che avrebbe fatto al caso loro e, cosa essenziale, si poteva presumere non avrebbe fatto storie sulla dote, praticamente inesistente. I genitori di Maddalena avevano annuito pensierosi: c&#146;erano altri figli, maschi, da sistemare, c&#146;erano i debiti contratti dal padre nelle sue partite &#150; frequenti ma quasi sempre sfortunate &#150; al &quot;faraone&quot; e ad altri giochi d&#146;azzardo, che guai se la cosa fosse arrivata all&#146;orecchio del marchese! Insomma, avevano dato carta bianca alla zia, accettando anzi con un certo entusiasmo (specialmente il padre) questa opportunità.<br>
              Maddalena era salita nella cameretta sotto la torre a controllare nel piccolo baule il bagaglio già predisposto per il viaggio; aveva obbedito, come sempre, ma senza entusiasmo. Proprio adesso, quando aveva quasi trovato il coraggio di parlare del suo segreto ai genitori&#133; E poi, quanto avrebbe dovuto restare in quella città sconosciuta da dove, l&#146;unica volta che vi si era recata da bambina, aveva riportato un&#146;impressione di confusione e di straniamento che le aveva fatto rimpiangere sospirando il suo borgo?<br>
              Cenarono nella sala in onore della zia; Giobatta era stato messo con i domestici, giù nelle cucine. Dopo, non ci si accontentò di stare a veglia, ma si attraversò il ponte levatoio, ancora abbassato, e ci si incamminò per la Contrada del Basso fra le occhiate curiose dei paesani. Era una bella sera di metà Giugno: il campanile di San Giovanni, cinto dai voli di rondini impazzite, sembrava a Maddalena una matita puntata nel cielo a scrivere arcane parole. Lei avrebbe desiderato arrivare fino a San Pietro, la su chiesa prediletta, ma i &quot;grandi&quot; avevano preferito avviarsi verso il borgo Lambro; Maddalena veniva qualche passo dietro di loro tenendo per mano il più piccolo dei fratelli, Giuseppe, di cinque anni. I grilli cantavano nei prati in riva al fiume, quasi un accompagnamento musicale ai lumini delle lucciole, sotto l&#146;argentea scorta di una luna sorta da poco; ma la giovane era triste e contava i minuti. Giacchè doveva partire, voleva che fosse subito; e il cuore le diceva che non sarebbe stato un viaggio qualsiasi. Fortunatamente, i &quot;grandi&quot; decisero di rientrare ancor prima che alla Chiesa dei Servi suonasse Compieta. Domani sarebbe stata una giornata faticosa: bisognava tornare in Castello e riposare un po&#146;.<br>
              Flop, flop, flop. Il trotto regolare dei due cavallini trasportava zia Caterina e Maddalena verso Milano. Giobatta, che all&#146;occorrenza sapeva fare da cocchiere, era montato in serpa e teneva le redini con sicurezza mentre la carrozzella procedeva fra il giallo dei campi di grano maturo e il verde dei prati segnato dalle linee lucenti delle marcite. A San Giuliano ci si fermò per far riposare le bestie; le signore, che non avevano appetito, rimasero in vettura sorseggiando una bevanda al limone nei bicchieri recati da una serva dell&#146;osteria.<br>
              Si ripartì: il tempo intanto stava cambiando e la calura immobile del primo pomeriggio era percorsa sempre più di frequente da cupi brontolii preannuncianti un temporale. Lì dentro ci si sentiva oppressi dal caldo e dall&#146;odore di cuoio delle pareti; la conversazione della zia, inoltre, non era certo delle più amene, però Maddalena si adoperava a parteciparvi con la dolcezza di sempre; ma il suo cuore era triste e la mente lontana.<br>
              <span class="citazione">&quot;Se ti affacci, da qui puoi già vedere il Duomo&quot;</span>. Lei si riscosse e sporse il capo: l&#146;enorme massa biancastra si stagliava sullo sfondo di un cielo percorso adesso da nuvole che sembravano cavalli lanciati al galoppo in qualche corsa sfrenata.<br>
              <span class="citazione">&quot;Ancora un&#146;ora, e siamo arrivati, signorina&quot;</span>, si sentì la voce di Giobatta. Melegnano era ormai lontana.<br>
              La casa della zia Caterina sorgeva in un quartiere a metà strada fra il palazzo della Biblioteca Ambrosiana e la Chiesa dedicata a S. Ambrogio; quindi piuttosto distante dal centro. Non si trattava certo di un palazzo splendido come quelli abitati dell&#146;aristocrazia, ma era pur sempre una dimora dignitosa, adatta alla famiglia di un importante funzionario governativo: lo zio Francesco, un ometto triste, schiacciato in casa dalla prorompente vitalità della consorte e che per reazione si era conquistato in ufficio la fama di duro e inflessibile.<br>
              Maddalena si installò docilmente presso gli zii, i cui figliuoli (la maggiore, una femmina, maritata a Padova, e un maschio, militare di carriera, stanziato con il proprio reggimento a Granz) avevano lasciato da tempo la casa. Si prestava di buon grado a quanto le chiedeva, o meglio imponeva, la zia: letture serali per propiziare il sonno, esecuzioni al clavicembalo dopo il pranzo, accompagnamento alle funzioni nella vicina Chiesa di S. Maria Podone, passeggiate sulle mura. Visite, poche: era estate, gli amici e conoscenti della famiglia si trovavano per la maggior parte fuori città, nelle case di campagna in Brianza o sui laghi. La zia, rimasta a Milano per impegni d&#146;ufficio del marito dal quale, pur maltrattandolo spesso, non sopportava di vivere a lungo separata, approfittava del periodo di calma per ammaestrare Maddalena sugli usi di società e soprattutto per sondarla, cercando di cavarle fuori i suoi progetti, ma inutilmente: calma, serena, gentile, Maddalena sembrava scivolare in questa nuova vita con la medesima imperturbabilità che ne avevano contrassegnato il comportamento a Melegnano. Ma, quando guardava dalla finestra della sua camera l&#146;ombra proiettata sul selciato a grossi lastroni di pietra dalle alte case che fiancheggiavano la via, riandava col pensiero alle stradine piene di sole del suo borgo, al balconcino che le era caro di fronte ai boschetti, alla striscia del fiume in lontananza. Entrando con la zia in una delle magnifiche chiese della città non poteva fare a meno, pur ammirandone le bellezze, di riandare con la mente alla &quot;sua&quot; chiesa di San Pietro, alle tante ore e alle emozioni là dentro vissute. Fino alle ultime, proprio nella passata primavera.<br>
              Sì, perché il segreto di Maddalena non era quello di un amore ignoto a tutti: o meglio, era quello di un amore tutto speciale. Il sogno segreto di Maddalena era di farsi monaca, e precisamente presso le Orsoline che avevano un convento giù, verso il Lambro. Nessuno, nemmeno la mamma, ne aveva avuto il minimo sentore; del resto la famiglia non era particolarmente religiosa, ma semplicemente osservante come le consuetudini dell&#146;epoca e il rango sociale imponevano. Soltanto Maddalena avrebbe potuto (ma tratteneva un pudore invincibile) raccontare come, in un modo che lei stessa non sapeva spiegarsi, dalle soste sempre più prolungate nella chiesa di San Pietro, tra l&#146;odore dell&#146;incenso e il profumo dei gigli sull&#146;altare accanto ai simulacri argentei dei Santi protettori, fosse andata nascendo in lei l&#146;aspirazione ad un Assoluto che non le pareva possibile trovare su questa terra. Frequentando appena poteva il convento delle Orsoline giù verso il Lambro, ne aveva colto l&#146;atmosfera silenziosa eppure pregna di qualcosa di totalmente nuovo, che non le era stato possibile ritrovare altrove. Tanto meno nelle seduzioni di quella grande città dove né il lusso degli equipaggi e delle toilettes delle dame, né le occhiate ammirative di qualche giovane avevano potuto scalfire l&#146;istintiva certezza della sua vocazione: quel sentirsi chiamata da Qualcuno più grande di tutti, a cui dedicare la propria vita.<br>
              Specialmente al tramonto, quando insieme alla zia compiva in carrozzino la rituale passeggiata sui bastioni, col profilo delle montagne azzurre là in fondo, il verde degli alberi e la sfilata di tetti cupole e campanili all&#146;interno del muraglione di cinta, dalla pienezza di vita che le riempiva il cuore Maddalena ricavava la percezione di essere nel giusto, di avere tra le mani il senso dell&#146;esistenza scoperto là nella chiesa del suo borgo, e sentiva che la sua strada era quella. In mezzo al frastuono delle vie, alle grida degli acquaioli, degli stagnini, agli schiocchi delle frustate dei cocchieri che le giungevano fin dal suo primo svegliarsi al mattino, lei, ragazza giovane e carina, desiderava silenzio e nascondimento, perdere se stessa per trovare un Altro più grande di tutti.<br>
              Eppure, incredibile a dirsi, in un&#146;epoca nella quale le monacazioni anche forzate erano si può dire all&#146;ordine del giorno, Maddalena presentiva che il suo caso sarebbe stato diverso, e difficile. C&#146;era anzitutto una lite che opponeva da anni al Convento, proprio a quello, la casata dalla quale il padre ricavava il proprio sostentamento; c&#146;era il fatto che su di lei, unica figlia femmina in una famiglia numerosa (e questo poteva anche essere un motivo valido), i genitori contavano molto&#133; Ma soprattutto c&#146;era &#150; lei lo sapeva bene e l&#146;aveva capito nonostante nessuno si fosse preso il disturbo di informarla &#150; la questione della dote: la congrua dote che, in caso di entrata in convento, avrebbe dovuto essere versata alla Suore, mentre lì a Milano si stava brigando per farle fare un matrimonio d&#146;interesse in cui la dote stessa sarebbe stata minima o addirittura non pretesa assolutamente. Aveva avuto ragione a temere questo viaggio, ma il peggio doveva ancora venire&#133;<br>
              Era arrivato l&#146;autunno, tutti i conoscenti della famiglia erano ormai rientrati a Milano e zia Caterina organizzò una serata in onore della sua giovane ospite. Maddalena indossò quella sera, faceva ancora caldo, il suo abito migliore, color cielo con la gonna a paniere. Molto scollato come usava allora, non la imbarazzava troppo anche perché aveva sotto mano un ricco scialle ricamato, dono della zia.<br>
              Il salone a pianterreno era ancora vuoto di invitati quando Maddalena scese abbigliata a pettinata secondo i consigli della zia. Rosa, la cameriera, aiutata da Giobatta stava sistemando accanto al muro i due divanetti rivestiti di raso a righine biancoazzurre per far posto a un numero maggiore di sedie. Il clavicembalo, al quale Maddalena nei giorni precedenti aveva dovuto esercitarsi più del solito, recava sul coperchio due candelabri d'argento; Maddalena accese personalmente le candele contemplandone l&#146;effetto sullo strumento: era una mediocre esecutrice, tuttavia le nuove musiche che aveva potuto conoscere nel periodo milanese l&#146;avevano molto colpita: quel Mozart, morto da poco tempo, era veramente straordinario.<br>
              Si attendevano parecchi invitati, e zia Caterina, scesa anche lei, ripetè ancora a Maddalena le solite esortazioni, con le quali l&#146;aveva letteralmente sommersa nei giorni precedenti: si guardasse dai giovanotti, per rivolgere invece la sua attenzione verso uomini più maturi e posati, capaci di rendere agiata e quindi felice la vita di una donna. Non doveva mostrarsi timida, ma neanche troppo sfacciata, mettesse pure l&#146;abito scollato e lasciasse in camera lo scialle, eccetera&#133;<br>
              Di lì a poco Giobatta introdusse nella sale don Gaspare Paglia, un ricco possidente sulla cinquantina, scapolo e non brutto, elegantemente imparruccato e incipriato. Giunsero quindi alcune coppie, i mariti funzionari imperiali come lo zio Francesco, le mogli tronfie e ricoperte di gioielli. Arrivò infine, da tutti riverito, il notaio Guarini, un anziano e grasso vedovo con due grosse borse sotto gli occhi e le mani perennemente ficcate nella tabacchiera d&#146;oro. Era anche presente il figlio di zia Caterina, venuto in licenza da Graz con due commilitoni, uno dei quali, il giovane Luitpold, che sapeva suonare il violino, si era già offerto di accompagnare Maddalena al clavicembalo.<br>
              Si avviò la conversazione, guidata dalla zia; Maddalena vi partecipava con il suo fare modesto ma senza eccessivo timore. Del resto gli argomenti non si scostavano dai soliti: salute, malattie, nascite, morti, qualche osservazione sugli spettacoli teatrali, ma soprattutto pettegolezzi a tutt'andare sugli assenti e magari, di soppiatto, anche su qualcuno dei presenti.<br>
              Vennero serviti vassoi sui quali tazze di cioccolata fumante (un lusso della zia per l&#146;occasione) stavano accanto a dolci della pasticceria più rinomata in città. A un certo punto, però, i giovani ufficiali portarono il discorso sulla politica, sulle cose tremende che stavano accadendo in Francia dove si sapeva che il re, dopo anni di rivoluzione, era stato imprigionato con tutta la famiglia. Ma zia Caterina, zio Francesco e gli altri ospiti, in perfetta sintonia fra loro, furono pronti a lasciar cadere l&#146;argomento, inadatto a dei buoni sudditi in casa dei quali il nome rivoluzione non doveva nemmeno venir pronunciato.<br>
              Maddalena, pregata, si avviò allora al clavicembalo seguita da Luitpold mentre lo sguardo esperto di don Gaspare e quello per la verità un po&#146; lascivo del notaio Guarini sembravano misurarne e valutarne le forme armoniose, i capelli pettinati a lunghi boccoli d&#146;oro, gli occhi vellutati.<br>
              Anche Luitpold l&#146;aveva fissata a lungo, fin dal primo incontro, e continuava a tenerla sotto la luce dei suoi begli occhi azzurri, teneri e rispettosi, che sembravano chiederle qualche cosa.<br>
              La musica sgorgò all&#146;unisono dai tasti del clavicenbalo e dalle corde del violino: come per miracolo, Maddalena si sentiva correre le dita sullo strumento con sicurezza nuova, quasi fosse condotta per mano dal giovane e sconosciuti mondi si schiudessero a loro&#133;<br>
              Maddalena si svegliò all&#146;alba. La neve aveva continuato a cadere nella notte, lei ne aveva ascoltato il fruscio e ne aveva avvertita ora la presenza nei suoni ovattati che le arrivavano dalla strada. Faceva freddo nella camera dove nel camino restavano solo poche braci e lo scaldaletto era assente (forse una vendetta della zia per il fallimento del suo progetto? scacciò subito il pensiero malevolo, che tuttavia sentiva non privo di fondamento). Riuscì comunque ad accendere la piccola bugia sul comodino, ed essa subito mandò per la stanza una debole luce. Il lunario appeso al muro accanto al letto segnava la data dell&#146;uno Febbraio. Già, pensò Maddalena, sembrava ieri quando si festeggiava il Capodanno 1793 ed ecco, siamo arrivati al secondo mese dell&#146;anno&#133;<br>
              Si inginocchiò sul pavimento e disse le preghiere, molto prolungate: seguiva già, d&#146;accordo con le Suore con le quali aveva continuato a corrispondere in segreto, certe regole che avrebbero dovuto assuefarla alla dura vita conventuale. Si lavò con l&#146;acqua semighiacciata della catinella e si vestì con l&#146;abito da viaggio grigio scuro. Pettinò a lungo i capelli biondi pensando con un bricciolo di rimpianto che presto, se fosse riuscita a convincere i genitori a darle il consenso, la sua bella chioma avrebbe dovuto essere sacrificata e il capo ricoperto per sempre da un velo. Il bagaglio era pronto: si ritornava a casa.<br>
              Maddalena dette uno sguardo alla cameretta dove aveva riposato per otto mesi; riposato però non era la parola giusta: specialmente dall&#146;autunno in poi la stanza era diventata per lei piuttosto un rifugio e aveva visto anche molte sue lacrime. Riandò alle visite sempre più frequenti di don Gaspare Paglia e del notaio, spalleggiati ciascuno da una propria fazione di sostenitori. Ripensò alla loro corte, discreta quella del possidente, più grossolana quella del Guarini nonostante il maggior prestigio sociale. Arrossiva ancora al ricordo di quella serata in cui, con il pretesto di offrirle uno spettacolo alla Scala (si trattava di un&#146;opera del Cimarosa) questo era venuto a prenderla in coupè, un coupè lussuoso foderato di velluto turchino dove, nonostante la presenza della zia che non si era accorta di niente (o fingeva di non vedere?) l&#146;anziano vedovo aveva tenuto per una volta le mani fuori dalla sua tabacchiera per tentare, purtroppo, di brancicare il corpo fiorente della ragazza&#133;<br>
              Infine, visti inutili i tentativi d&#146;altro genere, erano arrivate le richieste di matrimonio: entrambi i pretendenti, come si supponeva, non chiedevano dote di sorta.<br>
              Ripensò ai suoi rifiuti, alle lettere che giungevano da Melegnano da dove era anche arrivato un bel giorno nientemeno che suo padre, avvilito per una perdita al gioco più consistente del solito e che, in un colloquio a tu per tu, l&#146;aveva quasi implorata di cedere: ma lei ancora non aveva avuto il coraggio di rivelargli il suo vero proposito.<br>
              Rivide quei mesi di lotta. E, sullo sfondo, l&#146;immagine del giovane Luitpold, presto ripartito per Graz dopo averla accompagnata qualche sera al clavicembalo, e una volta anche a Messa: rivide i suoi occhi azzurri, quello sguardo misterioso che sembrava contenere una richiesta, peraltro mai formulata. E lei non aveva più avuto il coraggio di domandare sue notizie, ed era rimasta con l&#146;ombra di un dubbio che l&#146;aveva sfiorata più volte: aveva forse moglie lassù?<br>
              Tutto questo si era trascinato per mesi, con continui rinvii del ritorno a Melegnano nella speranza che lei potesse cambiare parere, ciò che non era avvenuto: a Maddalena non faceva difetto il carattere.<br>
              <span class="citazione">&quot;Un altro scampolo di vita passato&quot;</span> disse <span class="citazione">&quot;il peggio viene adesso&quot;</span>. Ma si sentiva pronta, provava solo il rammarico di avere dato un dolore ai genitori e anche alla zia, la quale malgrado il carattere dispotico aveva senza dubbio agito in buona fede, convinta di fare il suo bene.<br>
              Ecco che Maddalena sembra tentennare per un momento, mentre si credeva così ferma e sicura. Una figlia obbediente, come deve comportarsi? E se fosse tutto un frutto della sua immaginazione? E se la sua strada fosse quella del matrimonio? Non con il notaio e neppure con don Gaspare, che peraltro le spiace di meno: non potrebbe mai decidersi a questo per vili sebbene impellenti ragioni di denaro&#133; Ma esistono pure al mondo dei giovani buoni e sinceri (e le riapparve ancora il ricordo degli occhi di Luitpold, che sembrano domandarle qualche cosa).<br>
              <span class="citazione">&quot;Signorina Maddalena, signorina Maddalena&#133;&quot;</span> Rosa gridava salendo le scale di corsa, e intanto si sentiva provenire dal piano terreno il brusio di altre voci concitate, mentre giù nella strada, come Maddalena potè vedere scostando per un attimo i tendaggio della finestra, stava formandosi un capannello di persone che discutevano guardandosi attorno, quasi timorose. <span class="citazione">&quot;Signorina&#133;&quot;</span> Rosa era finalmente arrivata in cima e si precipitò nella camera senza neanche chiedere permesso, visibilmente turbata, levando le braccia al cielo: <span class="citazione">&quot;Che mondo, signorina: dicono che in Francia hanno tagliato la testa al re. Pensi che roba! Stasera in Duomo ci sarà una Messa di suffragio. Io quasi non ci credo, mi sembra una roba talmente grossa&#133; Ma in Francia in questi anni ne sono successe di tutti i colori, così dicono. E questa è la più grossa di tutte: pensi ammazzare un re! Io ci vado senz&#146;altro, alla Messa. A proposito, la signora zia ha detto che la partenza è rimandata perché tutta la famiglia deve essere presente, in Duomo, anche Lei, signorina: ma cos&#146;ha? si sente male?&quot;.</span><br>
              No, Maddalena non si sentiva male. Rifletteva soltanto a quello che le sembrava un segnale anche per lei. Non aveva saputo, non voleva sapere niente di quella cosa che chiamavano Rivoluzione. Non conosceva neanche il nome di quel Re (per il quale, ad ogni buon conto, avrebbe recitato un Rosario al più presto). Magari il popolo, pensò per pentirsene subito, avrà avuto i suoi motivi: non ricordava forse che a casa il suo maestro di disegno le aveva una volta mostrato il volume di un certo Voltaire che guai se l&#146;avessero visto i genitori, per non parlare delle sue care Suore? No, Maddalena non voleva sapere e non voleva giudicare. Voleva stare in silenzio, pregare, aiutare, meditare. Paura? Orgoglio? Aveva vissuto poco, ma abbastanza per capire che si deve scegliere: o immergersi nel flusso della vita dove possono succedere cose come questa, dove accade che gli uomini alternino quasi per partito preso saggezza e follia; oppure stare ai margini, per puntare verso un Assoluto che qui sulla terra non sarà mai possibile trovare.<br>
              Pensò per un attimo a testoline rosee di bambini, alle carezze di un uomo caro, bello, bellissimo, ma non faceva per lei. Lei voleva l&#146;Assoluto, voleva silenzio, silenzio e nascondimento. Anche nell&#146;ultimo convento della Bassa. Adesso ne era proprio sicura.<br>
              Aveva ormai lasciato alle spalle il Castello e andava verso la Piazza. Quanto era rimasta lì, otto minuti, otto mesi? Non avrebbe mai saputo se Maddalena era poi riuscita a coronare la propria vocazione al chiostro o se invece (cosa più probabile) aveva dovuto piegarsi alla volontà familiare, Monaca di Monza a rovescio.<br>
              Ma poi, questa Maddalena era una creazione della sua fantasia: perché stare a pensarci sopra più di tanto? Però in fondo, si disse, poco importava che Maddalena o qualcuna come lei fosse davvero esistita, lì o chissà quali altri luoghi nel passato. Quello che contava era aver tentato di riassaporarlo per un momento, questo passato al quale sentiva di appartenere oggi nell&#146;anno Duemila, sebbene non l&#146;avesse mai conosciuto. Lei, nell&#146;epoca di Internet e dei telefoni cellulari, si sentiva legata al mondo di Maddalena, anzi a tanti altri mondi ancora, indietro indietro fino alle epoche più remote; e, con lei i suoi simili, uomini e donne del Duemila, senza soluzione di continuità. Così come appartengono gli uni agli altri gli anelli d&#146;una catena, i chicchi del frutto d&#146;un melograno, gli oblò di una nave anche se ognuno si apre su un diverso spazio di mare.</p></td>
      </tr>
    </table></td>
  </tr>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="left" valign="top"><img src="/log2.png" width="100%" height="20"></td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#005A87">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="top"><img src="/log3.png" width="100%" height="20"></td>
  </tr>
</table>
<p class="piepagina"><a href="mailto:webmaster@aczivido.net">webmaster@aczivido.net</a></p>
</body>
</html>
