#!/usr/local/bin/php
<?
require("../include/var.inc");
$localpath="/parco";
require("../include/counter.inc");
?><html>
<head>
<title>Il parco dei giganti - il mulino a ruota</title>
<link href="/parco/parco.css" rel="stylesheet" type="text/css">
</head>
<body> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="14%" align="right" valign="top"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="right" valign="top"><img src="/parco/logo1.jpg" width="127" height="227"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo2.jpg" width="126" height="368"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
      <tr>
        <td align="right" valign="top"><img src="/parco/logo3.jpg" width="126" height="308"></td>
      </tr>
    </table></td>
    <td width="86%" align="left" valign="top" bgcolor="#FFFFFF"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="70%" align="left" valign="top" bgcolor="#D3E3B7"><img src="/parco/logo4.jpg" width="444" height="62"></td>
        <td width="30%" align="right" valign="top" bgcolor="#D3E3B7"><img src="/parco/logo5.jpg" width="205" height="58"></td>
      </tr>
    </table>      
      <table width="100%"  border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table>      
      <table width="100%"  border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="68%" align="left" valign="top"><table width="100%"  border="0" cellspacing="5" cellpadding="0">
            <tr>
              <td align="center" valign="top"><h1>il mulino a ruota ... storia</h1></td>
            </tr>
            <tr>
              <td align="left" valign="top"><p>I cereali costituivano la base dell'alimentazione, e non solo di quella popolare, fin dal tempo dei Romani che non si sentivano affatto sminuiti se non mangiavano carne: l'idea della nobilt&agrave; di questo cibo l'abbiamo ereditata dal medioevo e dalla sua aristocrazia di cavalieri-cacciatori. L'unico ammutinamento delle truppe di Cesare durante la conquista della Gallia scoppi&ograve; quando non arrivarono i rifornimenti e si dovette distribuire carne ai legionari, che si ribellarono chiedendo grano. Ne ricevevano una razione di 800 grammi al giorno che mangiavano in focacce cotte sulla pietra, tipo le attuali piadine, che avevano sostituito la pi&ugrave; antica puls, polenta di farro. Il pane entr&ograve; in uso un secolo dopo nelle citt&agrave; e il suo acquisto nei forni, assai apprezzato perch&egrave; diminuiva l'accensione di fuochi nelle case e i rischi d'incendio, parve un'originalit&agrave; come gli attuali fast-food &quot;da asporto&quot;.<br>
                    I Romani inventarono il mulino idraulico, costruito in muratura e con meccanismi di legno, verso la fine dell'impero, ma la diffusione di questo ritrovato tecnologico fu assai lenta nel medio evo per la scomparsa delle citt&agrave; e la polverizzazione dell'insediamento umano. Si continu&ograve; ovviamente a produrre il pane, ma non fu il modo prevalente di consumare i cereali. Solo i grani cosiddetti grossi, frumento e segale, si prestano ad una buona panificazione che, oltre al mulino, richiede un altro impianto fisso relativamente complesso e costoso: il forno. Nella primitiva societ&agrave; alto medioevale questi non erano disponibili ovunque. La rudimentale agricoltura dell'epoca faceva quindi molto assegnamento sui cosiddetti grani minuti: miglio, sorgo e pan&igrave;co pi&ugrave; adatti a produrre pappa che non pane. Fu una sorta di rinascita dell'antica puls, arricchita con verdure e legumi in una densa zuppa di cereali, popolare col nome du pulmentum in tutt'Italia.<br>
                    Dopo l'anno mille la popolazione crebbe rapidamente e soprattutto rinacquero le citt&agrave;, per cui i mulini idraulici presero a diffondersi in modo significativo verso le campagne a partire dai sobborghi urbani. La tecnologia, secondo il metro odierno, era assai modesta e non si potevano costruire grandi impianti, n&egrave; del resto la rete stradale e i carri disponibili consentivano trasporti a lunga distanza. Ciascun mulino serviva quindi un'area ristretta e piuttosto vicina. Il territorio novarese (e sangiulianese - nota dell'Associazione Culturale Zivido) &egrave; sempre stato ricco d'acqua e questo semplificava le cose, ma i fiumi non erano utilizzabili direttamente perch&egrave; avevano sempre un letto irregolare e a volte un alveo profondo, come il Ticino. Vennero dunque scavate delle rogge molinare, che servivano principalmente a questo scopo, in seguito si tagliarono delle piccole derivazioni alle rogge irrigue.<br>
                    Fino al Trecento i mulini furono costruiti prevalentemente in legno e spesso i pi&ugrave; piccoli erano flottanti, solo dal Quattrocento si riprese a costruirli sempre in muratura. Tutti i meccanismi, dalle grandi ruote a pale agli ingranaggi interni per trasmettere il movimento, rimasero per&ograve; in legno fino all'Ottocento. I mulini medievali riuscivano a lavorare non pi&ugrave; di 500 quintali di granaglie all'anno, in un periodo che durava da cinque a otto mesi, nel resto dell'anno non c'era abbastanza acqua. Una, al massimo due famiglie per gli impianti pi&ugrave; grandi, bastavano al funzionamento. Nonostante possano apparire oggi aziende modeste, si trattava di installazioni di notevole valore perch&egrave; vi si concentrava tutto il meglio della tecnologia disponibile ed in manufatti che, per l'epoca, erano di grandi dimensioni. Per il costo e la complessit&agrave; degli apparati e per la continua necessit&agrave; di manutenzione, il mulino preindustriale occupava una &quot;nicchia tecnologica&quot; paragonabile a quella coperta oggi dalle centrali elettriche. Va sottolineato che una tecnologia cos&igrave; avanzata e capillarmente diffusa non esisteva fuori dall'Europa. Per motivi economici i mulini dunque appartenevano a grandi proprietari, che di solito erano nobili, raramente ecclesiastici, a volte agli stessi signori dei villaggi, molto spesso, col decadere della feudalit&agrave;, ai comuni rurali.<br>
                    Dopo l'anno mille la popolazione crebbe molto rapidamente, ma l'agricoltura non riusc&igrave;, a lungo termine, a tenerne il ritmo. Nel giro di due secoli fin&igrave; impastoiata in un circuito vizioso a causa della mancanza di concime, non essendo riuscita ad integrarsi con l'allevamento di bestiame, che continu&ograve; ad essere praticato nei terreni incolti e con la transumanza verso le Alpi. La soluzione, sperimentata anche nel Novarese, sarebbero stati i prati, ma la forte spinta demografica ne blocc&ograve; la crescita. La superficie coltivata a cereali, in assenza di miglioramenti nella unitaria, venne estesa continuamente, divorando i boschi ed escludendo altre colture che non fossero la vite, giacch&egrave; il vino per il suo forte potere calorico ed il suo basso costo di produzione era usato come un vero alimento.<br>
                    La situazione alla fine del Duecento &egrave; bene illustrata dalle &quot;Grandezze di Milano&quot; scritte da Bonvesin della Riva. La citt&agrave; consumava 200.000 quintali di granaglie all'anno ed aveva 400 forni da pane. Bonvesin distinse i grani in due gruppi, frumento e segale da una parte, miglio e pan&igrave;co dall'altra: solo i primi venivano panificati. In particolare per il pan&igrave;co precis&ograve;: &quot;pan&igrave;ci unde derivatur pan&igrave;ceum&quot;, il paniccio, la zuppa con cui si mangiava e che meritava di essere citata per la sua diffusione ed importanza. Descrivendo le campagne di tutto il contado afferm&ograve; che vi si trovavano 900 mulini con 3.000 ruote in tutto, che non sarebbero bastati se l'abbondanza di castagne, pan&igrave;co e fagioli &quot;...non avessero nutrito ogni giorno moltissime persone al posto del pane&quot;. Il paniccio si cuoceva infatti con i fagioli dell'occhio, gli unici conosciuti prima della scoperta dell'America.<br>
                    Il grano indicato da Bonvesin bastava per una razione di 450 grammi di pane a testa al giorno, insufficienti a quell'epoca perch&egrave; c'era poco altro da mangiare. Senza pan&igrave;co, fagioli e castagne sarebbe stata fame nera. Il perch&egrave; di questo stato di cose lo spieg&ograve;, senza volerlo, lui stesso quando afferm&ograve; enfaticamente che pi&ugrave; di 30.000 coppie di buoi erano impiegate nella coltivazione del territorio e che i prati producevano una quantit&agrave; di fieno che ai suoi lettori sarebbe parsa incredibile, pari a quasi due milioni di quintali. ma quel fieno, che alui sembrava cos&igrave; tanto, non basteva per una decente alimentazione dei buoi, che dovevano essere dei veri scheletri, mangiando meno di 9 kg di fieno al giorno. Pi&ugrave; avanti infatti precis&ograve; che si nutrivano anche di fronde d'alberi; si comprende perch&egrave; Bonvesin non parli mai di mucche e nomini il latte una volta sola. Il bue, per arrivare ai 500 kg del suo peso forma, deve mangiare almeno 15 kg di fieno al giorno, producendo 20 kg di concime. Quei buoi forse arrivavano a 12, dunque non bastavano a letamere bene che 50.000 ettari di campi, pur essendo in grado di lavorarne 300.000. la diffusione del pan&igrave;co era dovuta anche al fatto che non richiedeva letame, inoltre si seminava in primavera e si raccoglieva in autunno frazionando anche il rischio di fallimento dei raccolti. Dunque non di tutti i cereali si faceva farina: gli statuti di Novara, scritti nella stessa epoca, fissarono in un coppo per staio (il 6,25% della quantit&agrave; lavorata) quella che rester&agrave; per secoli la mercede dei mugnai, precisando che lo stesso compenso spettava anche per la pilatura del pan&igrave;co e del miglio e del sorgo. Questi, come avvenne pi&ugrave; tardi per il riso, non hanno bisogno di essere macinati, basta sbucciarli con dei pestelli: il pan&igrave;co lavorato e pronto per l'uso si chiamava infatti pistum. Il pan&igrave;co richiedeva meno lavoro e sfruttava meno il terreno, anche rispetto alla segale e cresceva in appositi campi, i panighetti, dove si semnava in primavera in alternanza ai fagioli. Nei territori di Novara, Vercelli e Ivrea superava il miglio, cos&igrave; come la segale a sua volta superava il frumento perch&egrave; era pi&ugrave; facile prepararle il terreno, era meno faticosa da battere e richiedeva meno concime. Aveva un solo difetto: se l'annata era umida produceva la segale cornuta, un alcaloide allucinogeno che provocava le terribili e temutissime epidemie di fuoco di Sant'Antonio, cos&igrave; chiamato perch&egrave; i frati di quell'Ordine si erano specializzati nella sua cura con unguenti preparati col grasso di maiali appositamente allevati.<br>
                    Oltre alla facilit&agrave; di produzione dei grani minuti, altre ragioni militavano a favore delle polente e delle zuppe e contro il pane di cereali grossi, pur essendo questo pi&ugrave; nutriente. Si trattava infatti di un prodotto abbastanza pericoloso per le cattive condizioni di conservazione sia delle farine che dello stesso pane gi&agrave; cotto. Le farine si alterano molto pi&ugrave; rapidamente dei cereali in granella; inoltre i forni richiedono un notevole dispendio di combustibile per portarsi in temperatura, quindi il pane si preparava per una settimana o due ed essendo composto per il venti o trenta per cento di acqua, a seconda se di frumento o di segale, ammuffiva con estrema facilit&agrave;.<br>
                    I vantaggi del pan&igrave;co e del miglio sotto questo profilo erano notevoli: il miglio nelle sue varie specie ha il record assoluto di conservazione tra i cereali, pu&ograve; durare inalterato per cinque o addirittura dieci anni, se ben tenuto, si pu&ograve; pilare volta per volta con un mortaio ed un piccolo palo di legno, richiede meno combustibile per la cottura e la zuppa si consuma ogni volta appena fatta e quindi sterilizzata dalla cottura. Nelle campagne se ne faceva un gran consumo di zuppe, focacce, polente e farinate, avevano un'importanza pari a quella del pane. Il rilievo del pan&igrave;co &egrave; dimostrato da un altro statuto novarese, che tratta della misurazione con le mine, i cilindri di legno usati fino a pochi decenni or sono. Per misurare venivano immersi in un mucchio, dunque un conto era tirarli su colmi ed un altro rasi. La legge precis&ograve; quali prodotti andassero misurati in un modo e quali nell'altro. Frumento, segale, miglio, pan&igrave;co, pistum, meliga (allora si chiamava cos&igrave; il sorgo), legumi e semi di lino andavano misurati a raso, invece spelta, orzo, farro, avena, rape, cipolle e castagne a colmo. Il pan&igrave;co &egrave; l'unico prodotto citato sia allo stato grezzo che semilavorato ed &egrave; nel gruppo dei prodotti pregiati, che si misuravano a raso. Oggi pensiamo al miglio come ad un cibo per canarini, ma bisogna assolutizzare la situazione nella quale si vive.<br>
                    La situazione precipit&ograve; nel Trecento quando ormai l'alimentazione era basata quasi solo sui cereali soprattutto nelle citt&agrave;. Le cronache dell'epoca descrivono orripilate gli effetti della fame, il Libro del Biadaiolo dice: &quot;Si pascevano di cavoli e di sosine e di lattuga e d'altre radici d'erbe, di melloni e di diverse carni che di cavallo chi d'asino chi di bufola, ma senza alquanto di pane&quot;. L'Anonimo romano parla di cavoli e rape &quot;accomodati in sembiante di pane&quot; e di gente salvatasi grazie alle fave.<br>
                    Gi&agrave; in tempi normali si aggiungevano farine di legumi o di castagne al pane, in momenti di crisi si usarono bacche di carpini e biancospini, radici di fico, scorze di noci e di mandorle. Le descrizioni delle carestie per&ograve;, essendo opera di persone colte, descrivono sempre la situazione dal punto di vista urbano, diverso da quello delle campagne: quando si legge che i contadini vivevano di radici, si intende dire che mangiavano rape e carote.<br>
                    Un luogo comune delle cronache di carestia sono i cadaveri con l'erba in bocca, una spia dell'assoluta mancanza di abitudine dei cittadini a mangiare ogni tipo di verdura, genericamente considerata erba. Le ortaglie cominciarono a diffondersi nei sobborghi urbani dopo il 1350 e la loro superficie quintuplic&ograve; tra quella data e la fine del Quattrocento, mentre quella degli orti nei villaggi rurali rimase identica. Dopo la grande peste del 1348 le guerre non dettero tregua alle citt&agrave; che ebbero difficolt&agrave; a rifornirsi di cereali anche nel proprio contado: quello di Novara fu incendiato e raso al suolo due volte nel giro di pochi anni. I contadini trasformarono cos&igrave; un espediente momentaneo in un mutamento di lunga durata, inserendo quantit&agrave; vcrescenti di verdure nella propria dieta, visto che queste potevano essere coltivate a ridosso delle mura: l'orto produce cinque volte pi&ugrave; di un campo di cereali, ma i suoi prodotti non si conservano e sono troppo pesanti da trasportare, devono crescere vicino al mercato.<br>
                    La verza rimase poi per secoli la regina degli orti: era una pianta invernale ma da quell'epoca ed ancor di pi&ugrave; dal Cinquecento gli ortolani riuscirono a selezionarne molte variet&agrave; con le quali coprire un arco di tempo esteso quasi all'intero anno. Con la verza si preparavano vari tipi di zuppe che consentivano anche l'utilizzo delle parti pi&ugrave; scadenti del maiale come piedini, codini e balossi, cio&egrave; le ossa spolpate, che potevano essere recuperati e si vendevano a basso prezzo in citt&agrave;. La zuppa di verze, cos&igrave; insaporita, consentiva a sua volta l'utilizzo del pane raffermo, offrendo un'alternativa alle pappe di cereali anche per chi aveva problemi di denti, allora non risolvibili e molto diffusi.<br>
                    I disastri del Trecento ebbero anche effetti favorevoli, come l'aumento della produttivit&agrave; agricola, grazie all'abbandono delle terre marginali ed all'adozione di altre colture, rotazioni, e strumenti nonch&egrave; di nuovi contratti agrari. Il crollo demografico fece arretrare le colture ma i grandi boschi dell'alto medio evo, spazzati via dai campi di cereali, non si ricostituirono pienamente, vennero in gran parte sostituiti dai prati sui quali finalmente trovarono alimento i bovini. Che la situazione fosse migliorata lo dimostrano gli statuti di Biandrate, della fine del Trecento. Ad esempio per mietere segale, grano o avena da dare ai buoi o ad altre bestie occorreva il permesso del comune, che avrebbe sorvegliato l'operazione. Cento anni prima nessuno si sarebbe sognato di dare da mangiare grano ai buoi. In quel momento l'Europa cess&ograve; di essere una penisola dell'Asia. La sovrappopolata Europa della fine del Duecento doveva infatti essere molto simile alla Cina che, per sua sfortuna, non trov&ograve; mai modo di uscire dalla trappola demografica.<br>
                    L'equilibrio stabilitosi nel territorio novarese tra i grani grossi e quelli minuti cominci&ograve; ad alterarsi a partire dalla fine del Cinquecento, quando iniziarono ad espandersi le nuove colture del riso e del mais, anche se il riso rimase sempre un prodotto di lusso da vendere nei mercati urbani e la produzione del mais non si estese mai tanto da determinare, come nella Repubblica di Venezia, il passaggio alla polenta.<br>
                    Scoperto in America, il mais prese rapidamente il posto ed il nome del sorgo, al quale la pianta somigliava. Il sorgo era chiamato melicha, melga in dialetto ed il mais, avendo una pannocchia pi&ugrave; grande venne prima chiamato melg&ograve;n, poi a sua volta melga, quando il sorgo spar&igrave; del tutto. La traslazione progressiva del nome lasci&ograve; la sua traccia in quello del mais quarantino che, avendo la pannocchia pi&ugrave; piccola, fu chiamato milgun&igrave;n, piccolo melgone, non piccola melga.<br>
                    Il riso era noto fin dall'antichit&agrave;, ma come una costosa spezia. Gli Arabi l'acclimatarono nel Mediterraneo, ma i luoghi in cui si poteva produrre erano pochi e il prezzo rimase proibitivo. Si usava solo per piatti dolci da signori, con zucchero, mandorle, canditi o acqua di rose. era considerato anche una specie di medicina e non a torto, perch&egrave; contrasta l'acidit&agrave;. L'apparato digerente dei signori dell'epoca era bruciato dall'eccesso di spezie ed era gradito il benefico effetto rinfrescante di qualche leggero piatto di riso dolce.<br>
                    La pianta giunse da Valencia nel Quattrocento, e fu seminata alla ventura nelle parti esterne delle &quot;valli&quot; di Ferrara, Bologna, mantova e Verona, le quali per&ograve; non erano che paludi stagionali. Nella Padania occidentale il riso trov&ograve; invece un ambiente unico: il sistema di drenaggio e irrigazione dei prati, creato alla fine del medio evo, che venne adattato per servire anche le risaie. Nella Padania orientale i prati irrigui non c'erano e molti confondevano risaia e palude, senza rendersi conto che in Piemonte e Lombardia la risaia era una coltura di bonifica che fece sparire tutte le paludi esistenti.<br>
                    Il vero problema del riso non era il danneggiamento della salute ma lo sconvolgimento delle strutture sociali. Era una coltura di piantagione, anche se meno disumana di quelle tropicali perch&egrave; senza schiavi, ma era possibile solo in grandi propriet&agrave; e con il lavoro di braccianti. Cancellava i coltivatori diretti e costringeva parte della popolazione ad emigrare, ma restando vicina per le operazioni di massa come la monda, il trapianto e il raccolto.. Chi coltivava il riso non lo mangiava abitualmente, come tutti i prodotti di piantagione. Nel Cinquecento, mentre il suo prezzo scendeva e cessava di essere considerato una spezia, si cominci&ograve; a darne una certa quantit&agrave; in paga ai contadini di quel serbatoio di manodopera stagionale. Essi, a casa loro, coltivavano all'asciutto e mangiavano segale e miglio, la prima forma di pane, il secondo in forma di zuppa. Quando ebbero in mano qualche sacchetto di riso non lo usarono in piatti dolci come i signori. I poveri non potevano sprecare i loro pochi soldi in zucchero, mandorle, cannella e canditi, neppure nelle feste solenni, per cui usarono il riso nel solo modo in cui sapevano cucinare un cereale pilato: il paniccio coi fagioli dell'occhio, sostituiti dai borlotti nel Seicento inoltrato, quando le le qualit&agrave; americane di fagioli presero il sopravvento. Il riso era pi&ugrave; buono del pan&igrave;co ed il piatto si afferm&ograve; facilmente, ma nei limiti imposti dal prezzo del prodotto: la paniscia novarese &egrave; un piatto popolare ma &egrave; anche un piatto festivo.<br>
                    Il pan&igrave;co, che costituiva circa un ventesimo della produzione di cereali, scomparve presto ed il miglio non tard&ograve; molto a seguirlo. Del resto si somigliavano molto e gli stessi nomi dimostrano una certa confusione: quello scientifico del miglio &egrave; pan&igrave;cum miliaceum, mentre quello del pan&igrave;co &egrave; setaria italica. Si tratta di un prodotto tipicamente nostrano, infatti i francesi lo chiamano miglio d'Italia. All'inizio del Seicento il &quot;quinternetto del grano minudolo&quot; di bellinzago, robusto villaggio di coltivatori diretti, cominciava col miglio, proseguiva con la meliga elencando per ultimi &quot;panigho e fasoli&quot;, non a caso in colonne affiancate.<br>
                    Il piatto tipico delle province risicole ad occidente del Ticino ha funzioni ed origini diverse da quelle dei risotti cittadini, come quello alla milanese. La paniscia non &egrave; un primo, ma un piatto unico e un piatta popolare di campagna. Usa il lardo anzich&egrave; il burro, una zuppa di fagioli e verdure anzich&egrave; il brodo di carne di manzo, la mortadella di fegato e non il midollo di bue e perfino il vino rosso anzich&egrave; quello bianco, infine vuole formaggio grattugiato. Questo piatto, diffuso nelle varianti della panissa vercellese e della panizza valsesiana, esiste in quasi perfetta coincidenza con l'area in cui nel medio evo era pi&ugrave; estesa la coltivazione del pan&igrave;co, che comprende i territori di Novara, Vercelli ed Ivrea.<br>
                    La sua nascita fu probabilmente un'involontaria conseguenza della maggiore diffusione dell'uso del pane in campagna. Questo fu a sua volta una conseguenza non intenzionale della espansione della coltura del mais. Questo cereale aveva chicchi molto grossi ma fu classificato tra i grani &quot;minuti&quot; perch&egrave; accomunato ad essi dalle sue caratteristiche fondamentali: il raccolto autunnale, la qualit&agrave; modesta, il prezzo basso e la scarsa attitudine alla panificazione.<br>
                    Alla fine del Cinquecento la congiuntura economica si mise al brutto e ci rimase per un secolo e mezzo. Il mais rendeva da quindici a diciotto volte la semente ed era una tentazione troppo forte per i piccoli coltivatori. Lombardia orientale e Veneto lo adottarono in via esclusiva, diventando terre di mangiatori di polenta, mentre nelle nostre regioni continu&ograve; anche la coltura della segale, che era molto richiesta dalle vicine zone di montagna, Valsesia, Verbano, Cusio ed Ossola, che non ne producevano a sufficienza. Il mais riusc&igrave; solo ad eliminare tutte le variet&agrave; di miglio, spianando la strada alla sostituzione del pan&igrave;co col riso.<br>
                    Nel 1606 le scorte dei contadini di Bellinzago erano costituite da miglio per pi&ugrave; della met&agrave;: meno di cent'anni dopo era scomparso. Ai nostri contadini rimasero dunque segale e mais. Quest'ultimo per&ograve; a differenza del miglio, aveva chicchi grossi e senza buccia per cui doveva essere comunque macinato in un mulino e trasformato in farina. Con la farina gialla del mais si poteva fare la polenta, ma questa nel Novarese non ebbe mai molto successo, si cominci&ograve; a usarla solo nell'Ottocento e non conobbe neanche in seguito una grande diffusione. I contadini novaresi preferirono unire il mais a una pari quantit&agrave; di segale per farne pane di mistura, che divenne il loro alimento principale.<br>
                    L'impulso, evidente nel Seicento, alla costruzionje di nuovi mulini e di numerosi forni comunali va probabilmente collegato alla scelta del pane anzich&egrave; delle zuppe o della polenta da parte dei rurali novaresi: fino alla fine del Cinquecento il pane era rimasto minoritario nelle campagne. Del resto conservarlo dopo la cottura non era facile ed i nostri contadini, compiendo questa scelta originale, si presero una grana non da poco. Il pane doveva durare almeno una settimana e andava tenuto all'aria aperta, altrimenti ammuffiva. ma gli edifici pullulavano di topi e per difenderlo occorrevano o dei contenitori a gabbia, che in questa zona non ebero successo, oppure i &quot;ridotti da pane&quot;, tavolati posti a mezza parete per impedire ogni possibilit&agrave; d'accesso, che in un inventario cinquecentesco novarese di attrezzatura da cucina cita come &quot;... certe asse per reponere suso el pane&quot;.<br>
                    In citt&agrave; il passaggio completo al pane era avvenuto prima che in campagna, le zuppe di cereali erano scomparse alla fine del medio evo e come piatto caldo erano state sostituite da quelle di verdura, in particolare di verze. Anche il pane che mangiava il popolino di citt&agrave; veniva chiamato &quot;di mistura&quot;, ma si trattava di un articolo di qualit&agrave; molto migliore: i cereali miscelati erano infatti il frumento e la segale. Si deve tener presente che il pane allora era diverso quasi in ogni centro urbano, per esempio a Busto Arsizio quello popolare era per tre quarti di frumento e un quarto di mais, a Vigevano invece era di sola segale. Ovviamente i ricchi usavano ovunque il pane bianco di solo frumento.<br>
                    I consumi di pane erano molto forti, in tempi normali superavano i 400 grammi a testa al giorno e raggiunsero il massimo verso la met&agrave; dell'Ottocento con circa 600 grammi. Ogni anno era dunque necessario macinare almeno due quintali di cereali per abitante e questo faceva s&igrave; che la molitura fosse la pi&ugrave; importante industria dell'epoca. Per i comuni rurali il possesso di uno o pi&ugrave; mulini era di fondamentale importanza, come lo era il possesso dei forni da pane e di estensioni pi&ugrave; o meno vaste di terre comuni a pascolo o bosco. L'amministrazione si procurava cos&igrave; delle entrate sicure senza aumentare le tasse, evitava che i redditi di questi beni defluissero all'esterno della comunit&agrave; impoverendola e poteva impedire che il prezzo delle prestazioni venisse maggiorato oltre le possibilit&agrave; degli abitanti.<br>
                    I mulini venivano affittati con regolari aste pubbliche a degli imprenditori specializzati per un periodo di tre o quattro anni. I molinari dunque si spostavano abbastanza di frequente anche se potevano riuscire ad aggiudicarsi pi&ugrave; appalti successivi dello stesso impianto. Il fittabile del mulino oltre al canone d'affitto doveva pagare l'acqua e tenere pulito il canale. Poich&egrave; i mulini si trovavano spesso a notevola distanza dal centro abitato, di solito il mugnaio era tenuto ad andare a prendere i grani a domicilio dei clienti ed a riportarvi la farina. Il compenso nel Novarese era normalmente di un coppo per mina, cio&egrave; di un sedicesimo del grano macinato (6,25%). I canoni d'affitto erano abbastanza elevati, potevano giungere ad un terzo dei ricavi lordi dell'esercizio e dovevano essere pagati in contanti. Si trattava quindi di un'attivit&agrave; redditizia ma non esente da rischi: essendo pagati in natura i mugnani dovevano improvvisarsi mercanti ed in caso di crisi potevano trovarsi in difficolt&agrave;. Stante la brevit&agrave; dei contratti cercavano di guadagnare il pi&ugrave; possibile e pare che avessero una spiccata tendenza a fare la cresta sul macinato. Almeno cos&igrave; credevano tutti: il mugnanio della leggenda popolare, oltre che grasso e bianco di farina, &egrave; sempre un ladro matricolato.<br>
                    I mulini avevano due o spesso tre ruote e diverse macine, di dimensioni e grana differenti per i divesri tipi di cereali da macinare, sovente anche una pista per lavorare il risone, diretta discendente della macchina a pali per pestare il miglio. Le macine, vero cuore del mulino, erano prodotte per lo pi&ugrave; in una zona specializzata delle Prealpi Lombarde ed erano molto costose anche a causa del trasporto. Molti contratti di affitto prevedevano lo smontaggio e la pesatura ad ogni cambio di fittabile, per calcolare il consumo ai fini del rimborso al proprietario. Quasi sempre a valle del mulino c'era un appezzamento di prato, raramente inferiore ad un ettaro o superiore a tre, affittato a parte e che serviva ad alimentare le bestie da tiro per i carri. Per riciclare gli scarti di lavorazione i molinari potevano inoltre allevare maiali e polli ma in numero prefissato, in quanto non era gradito che producessero pi&ugrave; di quanto bastava al consumo familiare.<br>
                    Nonostante la complessit&agrave; degli strumenti, gru, argani e viti di taratura e la continua manutenzione, le mole minerali, per quanto accuratamente scalpellate per regolarizzarne la forma, non davano un prodotto di buona qualit&agrave; anche perch&egrave; i meccanismi di legno trasemttevano il moto in modo irregolare. La farina non era omogenea e conteneva anche una certa quantit&agrave; di corrosiva polvere minerale, frutto del consumo delle mole. Inoltre le perdite di lavporazione erano piuttosto forti. Esperimenti ufficiali eseguiti a Novara all'inizio dell'Ottocento attestano che da 100 kg di granaglie si ottenevano solo 95 kg di farina grezza che doveva poi essere burattata per separarla dalla crusca.<br>
                    Ancora nella prima met&agrave; dell'Ottocento il processo di burattazione non avveniva nei mulini, che consegnavano la farina grezza ai clienti. In citt&agrave; e nei borghi maggiori erano i prestini a burattare le farine prima di procedere alla panificazione, nei villaggi minori erano le singole famiglie a proveddere. Ne ricavavano la crusca per l'alimentazione del maiale domestico e consegnavano la farina al forno che impastava e cuoceva il pane trattenendo in pagamento un quindicesimo del prodotto. Poich&egrave; la macinazione era gi&agrave; costata un sedicesimo in totale il 13&amp; della scorta di cereali di ogni famiglia veniva speso per trasformare le granaglie in pane. La sua qualit&agrave; dipendeva essenzialmente dalle scelte effettuate nella burattazione, che era un processo a pi&ugrave; fasi. Tra i due estremi del fior di farina e della crusca si potevano ottenere fino a sei gradazioni diverse di prodotto.<br>
                    Il fior di farina superava di poco il 50% ed a seconda delle situazioni economiche dei luoghi e delle epoche gli si univa pi&ugrave; o meno farina di seconda qualit&agrave;. In tempo di pace non si panificava molto pi&ugrave; del 70% del prodotto e il resto si dava ai maiali, per non abbassare troppo la qualit&agrave; del pane. In tempo di guerra sono documentate panificazioni fino ad un massimo dell'85% del prodotto grezzo. Pi&ugrave; farina di seconda qualit&agrave;, o peggio pi&ugrave; crusca, entrava nel pane, pi&ugrave; questo riusciva pesante, umido, di difficile digestione e facile ad ammiffire. Il pane di fior di farina cresceva solo del 15% per l'acqua che vi restava inclusa dopo la cottura, contro il 30% del pane di seconda qualit&agrave; ed il 50% del pane di guerra o di carestyia. Accadeva anche di peggio, l'abitudine al pane era tale che nei frequenti tempi di penuria si aggiungevano ai cereali le castagne, le ghiande e perfino le bucce di lupini macinate pur di ottenere qualcosa che assomigliasse da lontano al pane.<br>
                    Continuando ad usare come esempio di comune rurale quello di Bellinzago, uno dei meglio documentati, si deve osservare che il paese fino al Cinquecento ebbe un solo mulino idarulico nella valle del Ticino, al termine della strada della Canova: il Mulino Vecchio. Era sufficiente perch&egrave; il paese aveva meno di mille abitanti i quali macinavano solo la segale, che costituiva la met&agrave; circa del consumo di cereali, mentre il miglio era talmente minuto da rendere almeno in parte preferibile la pilatura domestica. Le cose cambiarono nel Seicento: il paese visse una fase di forte aumento della popolazione contemporanea alla progressiva sostituzione del miglio con il mais, che venne mescolato alla segale nel pane di mistura. Un mulino non bastava pi&ugrave;: la comunit&agrave;, che era politicamente assai robusta perch&egrave; formata per il 90% da proprietari coltivatori diretti, decise di costruirne un secondo: il Molinetto.<br>
                    Nel 1619 tutti gli abitanti validi furono mobilitati dai consoli e scesero nella valle del Ticino per una settimana, comprese le donne, a scavre una derivazione della roggia molinara. Il mulino fu alimentato acquistando una parte delle acque e sottraendo il resto, approfittando dei disordini della guerra dei Trent'anni. L'edificio stesso sorgeva in territorio di di cavagliano, che allora era un comune autonomo, anche se si trattava di terreni abbandonati. All'inizio del Settecento il comune possedeva ambedue i mulini: quello vecchio - che era appartenuto ai feudatari Del maino - doveva essere stato acquistato dalla comunit&agrave;, insieme a quasi tutti gli altri diritti signorili a contenuto economico.<br>
                    Il possesso pubblico dei mulini, molto diffuso in tutto il basso Novarese, dur&ograve; fino alla fine del periodo napoleonico. La loro privatizzazione avvenne in blocco quando il governo vendette quasi tutti i beni comunali per mettere insieme denaro e formare nuovi eserciti, per salvare l'impero dopo le sconfitte in Spagna ed in Russia. I due mulini di Bellinzago furono venduti per 10.000 lire ciascuno, poco pi&ugrave; di met&agrave; del loro valore di mercato; uno fu acquistato dallo stesso fittabile, l'altro dal grande proprietario novarese Gaetano Morbio.<br>
                    Oggi siamo abituati ad associare l'idea del mulino a quella della bianca farina di frumento ma in verit&agrave; per secoli il frumento fu macinato ed usato ben poco. Esso &egrave; senz'ombra di dubbio il cereale pi&ugrave; nutriente, con un po' di legumi ed un bicchiere di vino si pu&ograve; sostituire carne e pesce, mentre il mais o peggio la patata non sono in grado di farlo. Inoltre &egrave; anche il pi&ugrave; gradevole da mangiare ma, sia per motivi climatici (faceva pi&ugrave; freddo) che per ragioni economiche (una lunghissima recessione), tra la fine del Cinquecento e la fine del Settecento il consumo di frumento diminu&igrave; e non di poco: nel 1774/78 il Prestino di Novara smalt&igrave; 1.200 quintali di frumento all'anno, mentre del 1580 il consumo era stato di 3.500 quintali. I cereali inferiori avevano quasi totalmente conquistato il mercato. La loro ritirata, almeno dal mercato urbano, inizi&ograve; prima della rivoluzione francese.<br>
                    Il pane di mistura e di segale erano di libera produzione, mentre il pane bianco si poteva fabbricare solo nel Prestino della Privativa. Era un diritto della Finanza statale appaltato in monopolio: la bardatura protezionistica fissava all'appaltatore prezzi e profitto, modesto ma garantito, come si usava nell'Ancien R&eacute;gime. Nel 1780 il Comune la riscatt&ograve; versando una somma enorme allo Stato perch&egrave; la domanda di pane bianco aveva improvvisamente preso a crescere e la soppressione del monopolio favoriva l'aumento dello smercio . Per fare fronte al debito contratto dal comune fu costituito un consorzio di garanzia nel quale entrarono venti panettieri e sei fabbricanti di biscotti, tutti acquisivano il diritto a produrre pane bianco. Il ceto medio dei bottegai/artigiani aveva capito fin dai primi cenni di ripresa economica che la prospettiva di lungo periodo era quella di un completo passaggio al pane bianco di frumento.<br>
                    Infatti nell'et&agrave; napoleonica a Novara ormai met&agrave; degli abitabnti mangiava pane bianco: il progresso era stato enorme perch&egrave; vent'anni prima ne avevano fatto uso solo poche centinaia di persone. Nelle campagne invece ancora l'80% della popolazione mangiava pane di mistura. Il consumo medio in citt&agrave; era di oltre 400 grammi al giorno: anche i ricchi ne mangiavano molto, ad esempio i convittori del Liceo, giovani maschi della classe dirigente, nel 1812 ne consumavano 600 grammi a testa al giorno. La qualit&agrave; del pane tra il 1780 ed il 1810 miglior&ograve; nettamente, perch&egrave; lo stretto contatto con la pi&ugrave; progredita societ&agrave; francese introdusse sia una nuova tecnologia molitoria che un nuovo modo di fare il pane.<br>
                    Il pane bianco tradizionale novarese era di &quot;pasta dura&quot; con la crosta sottile, lisvcia e lucida e l'interno stratificato e friabile. A questa si contrappose la pasta molle alla francese, con la crosta spessa ed irregolare e la mollica morbida e spugnosa. Nel 1810 quattro quinti del pane bianco si producevano ormai alla francese, la pasta dura era confinata ai panini di lusso, un ruolo che del resto le era congeniale perch&egrave; richiede farina della migliore qualit&agrave;, essendo simile alla sfoglia. Nelle campagne invece l'acquisto del pane, che in citt&agrave; era la regola, costituiva un'eccezione. Sia i proprietari che gli affittuari dopo il raccolto accantonavano la scorta per l'anno successivo, i salariati fissi ricevevano da met&agrave; a tre quarti della paga in cereali ed anche gli artigiani tendevano a costituirsi una scorta, spesso erano addirittura pagati in natura dai loro clienti.<br>
                    In quegli anni era stata importata dalla Francia una pi&ugrave; progredita tecnologia molitoria che consent&igrave; di costruire impianti di capacit&agrave; produttiva maggiore, fino a 4.000 quintali annui, circa il doppio dei mulini tradizionali e che riuscivano a lavorare per un arco di tempo pi&ugrave; lungo di un terzo, sfruttando gli stessi canali e gli stessi edifici. La qualit&agrave; della farina miglir&ograve; sensibilmente e divenne pi&ugrave; omogenea.<br>
                    La diffusione delle nuove tecniche fece venir meno la necessit&agrave; di burattare in pi&ugrave; fasi le farine ed i vecchi buratti di crine vennero sostituiti progressivamente dai pi&ugrave; moderni setacci in velo di seta che in un'unica fase separavano la crusca dalla farina da panificare. la semplificazione del processo ed i maggiori volumi da lavorare spinsero verso la meccanizzazionemdella stacciatura che cess&ograve; di essere la prima fase della panificazione per divenire invece l'ultima fase della molitura. I mulini si arricchirono cos&igrave; di nuovi macchinari che, negli impianti pi&ugrave; vecchi, furono installati al piano superiore. Nel 1827 solo l'1% della farina lasciava il mulino gi&agrave; stacciata, nel 1869 la percentuale era salita al 62%. Novara, sonnacchiosa cittadina rurale, divenne nel corso dell'ottocento una delle punte di diamante dello sviluppo economico nazionale. L'impatto del nuovo secolo fu quindi assai diverso tra citt&agrave; e campagna. Nel 1817 termin&ograve; l'era delle periodiche carestie e lo standard alimentare di un anno normale pot&egrave; essere mantenuto per tutta la vita pur rimanendo sempre lo stesso: fu una svolta paragonabile per importanza a quella verificatasi nel nostro secolo in India dopo il 1965. Innesc&ograve; infatti una forte crescita della popolazione: la produzione insufficiente cess&ograve; di essere il problema principale e fu sostituito da quello di una pi&ugrave; equa distribuzione. Ma lo standard alimentare non cambi&ograve;, quindi non mutarono le basi della cucina contadina, fu quella di citt&agrave; a diventare la destinataria privilegiata dei mutamenti.<br>
                    Dopo la met&agrave; del secolo venne importata l'ancora pi&ugrave; avanzata tecnologia molitoria americana, che consentiva di costruire mulini capaci di lavorare anche 10.000 quintali di grano all'anno e ben 300 giorni di operativit&agrave; effettiva. Le perdite di lavorazione si ridussero al 2% e la qualit&agrave; della farina miglior&ograve; ancora. varcata questa soglia si entr&ograve; nel campo dell'industria moderna che, del resto, stava sviluppandosi anche in altri comparti come quello tessile e meccanico. Il futuro dei mulini di paese era segnato e si avviava al tramonto l'era delle famiglie di piccoli mugnai indipendenti.<br>
                    Alla fine dell'Ottocento nella citt&agrave; di Novara il numero degli addetti ai mulini era lo stesso di centocinquanta anni prima, ma lavoravano un volume di granaglie otto volte superiore ed ormai erano per lo pi&ugrave; salariati alle dipendenze di un proprietario trasformatosi in industriale. Del resto i consumi pro capite di pane erano in continuo calo, negli anni Ottanta ormai erano scesi a 300 grammi a testa al giorno mentre si era sviluppato il consumo della pasta che richiedeva farine lavorate industrialmente.<br>
                    Quale fosse rimasta la situazione nelle campagne lo pu&ograve; dimostrare, meglio di qualunque ragionamento, un brano dello spezzone novarese della celebre inchiesta agraria Jacini, del 1880, affidato al massimo esperto locale, Oreste Bordiga, il quale dedic&ograve; anche alcune pagine all'alimentazione: &quot;I semplici giornalieri del piano mangiano quantit&agrave; notevoli di pane di mais misto con segale e dove predomina la risaia quello di risina mescolato anch'esso col detto grano. Sono i pani di kg. 1,5 di peso ed anche pi&ugrave; ed un uomo adulto ne mangia in un girno uno intiero senza pensarvi. la polenta, la minestra di riso e fagioli, il cacio di qualit&agrave; inferiore, il lardo e la carne del maiale macellato a carnevale e conservato anche solo per met&agrave; accompagnano il pane del contadino. D'altra carne Esso non fa uso, eccettuato forse a Natale e nel giorno della festa del luogo ed anche questa &egrave; di qualit&agrave; inferiore; invece mangia in quantit&agrave; notevole pesce salato e rane e pesci raccolti in risaia durante l'estate. Abbondante &egrave; pure l'uso di verdure, di pomi di terra, cipolle, agli e rape prodotti molte volte nell'orto concesso dal padrone o comprati in paese. Il massaio ed il piccolo affittuario si alimentano alquanto meglio; usano bens&igrave; di pane di granoturco e di segale, ma non di quello di risetto; mangiano in maggior quantit&agrave; la carne di maiale e fanno pi&ugrave; largo consumo del latte e dei suoi prodotti, avendo molte volte una vacca in istalla&quot;.<br>
                    A Novara citt&agrave; invece, tra il 1860 e il 1875 nella prima fase della rivoluzione industriale, si affermarono i consumi nuovi, espressione della societ&agrave; contemporanea: pane bianco, pasta, pollo, latte fresco, caff&egrave;. Una delle maggiori differenze tra citt&agrave; e campagna era proprio quella del pane quotidiano. Bordiga affermava che il pane di campagna era pieno di difetti, quello di citt&agrave; invece era ormai di ottima qualit&agrave;. I mulini moderni producevano una farina non solo migliore, ma pi&ugrave; omogenea per cui non fu pi&ugrave; necessario separare il roggiolo dal fior di farina se non per le esigenze della pasticceria. L'avanzata del pane bianco era ormai giunta alla vittoria finale, dopo un secolo di rimonta.<br>
                    Negli anni 1865-69 in citt&agrave; i grani inferiori costituivano solo il 19% del consumo di cereali, livello che scese ancora all'8% negli anni Ottanta. Come per il vino il miglioramento della qualit&agrave; comport&ograve; la diminuzione del consumo individuale in termini di quantit&agrave;. Bordiga segnalava ancora consumi altissimi di pane di cattiva qualit&agrave; nelle campagne, mentre in citt&agrave; scendevano tra gli anni Sessanta e Ottanta da 400 a 330 grammi a testa al giorno.<br>
                    I risultati dell'indagine governativa effettuata a Novara nel 1868, quando Quintino Sella var&ograve; la famigerata tassa sul macinato e quindi tutti imulini vennero posti sotto controllo, sono estremamente interessanti perch&egrave; mostrano dal vivo la trasformazione in atto delle tecnologie molitorie e la differenza tra i mulini tradizionali e quelli moderni. I dati sono talmente espliciti da non avere bisogno di commenti.<br>
                    I mulini moderni, di tipo francese o americano, lavorano solo frumento. lentamente e progressivamente i superstiti mulini tradizionali, scomparsa la segale, finirono col restare confinati alla macinatura del mais. Col nuovo secolo inizi&ograve; addirittura la fine dei mulini idraulici perch&egrave; gli impianti moderni vennero sempre pi&ugrave; costruiti per funzionare con la corrente elettrica o con motori a scoppio. I rari esemplari sopravvissuti si ridussero a lavorare cereali per uso mangimistico animale e non essendo redditizi finirono per scomparire uno dopo l'altro. Il piccolo mugnanio indipendente, un tempo tra i benestanti del villaggio, dovette cambiare mestiere o conservare un livello di vita che, rispetto al progresso generale, divenne sempre pi&ugrave; povero. Si pu&ograve; considerare un miracolo che in tali condizioni sia sopravvissuto qualche mulino idraulico in grado di funzionare ed &egrave; quindi doveroso conservare questi rari esemplari di impianti che furono per secoli una vera incubatrice del progresso tecnologico.<br>
                    <br>
                (di Giampiero Morreale, tratto da &quot;Mulino vecchio di Bellinzago&quot;, a cura Ente Gestore Parco Naturale della Valle del Ticino, Tipografia Italgrafica, Novara, aprile 2001)</p></td>
            </tr>
          </table></td>
          <td width="2%">&nbsp;</td>
          <td width="30%" align="center" valign="top"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><img src="/parco/logo7.jpg" width="254" height="22"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#8DC919">&nbsp;</td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#8DC919"><img src="image/bor09.jpg" width="230" height="160"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#8DC919">&nbsp;</td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="/parco/logo8.jpg" width="254" height="22"></td>
            </tr>
          </table></td>
        </tr>
      </table>      
      <table width="100%"  border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="70%" align="center" valign="middle"><a href="/parco/index.php">home</a></td>
          <td width="30%" align="left" valign="top"><img src="/parco/logo6.jpg" width="220" height="54"></td>
        </tr>
      </table>      </td>
  </tr>
</table>
<p class="piepagina"><img src="../sangiulianomil/ACZppplogo.JPG" width="61" height="95"><br>
  sito di propriet&agrave; della <a href="../../index.php" class="piepagina">Associazione Culturale Zivido</a><br>
  <a href="mailto:webmaster@aczivido.net" class="piepagina">webmaster@aczivido.net</a></p>
</body>
</html>
